#!/usr/bin/env python3

from http.server import BaseHTTPRequestHandler, HTTPServer
import os
import random
import textwrap

html_template = textwrap.dedent('''\
    <html>
    <head>
        <title>Greetings to the world</title>
    </head>
    <body>
        <h1>Greetings to the world</h1>
        <p>Hello, world!</p>
        <p>My process id is {}.</p>
        <p>Here is a random number: {}</p>
    </body>
    </html>
''')


class HelloRequestHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        if self.path != '/':
            self.send_error(404, "Object not found")
            return
        self.send_response(200)
        self.send_header('Content-type', 'text/html; charset=utf-8')
        self.end_headers()
        my_pid = os.getpid()
        random.seed()
        a_random = random.random()
        response_text = html_template.format(my_pid, a_random)
        self.wfile.write(response_text.encode('utf-8'))


server_address = ('', 8000)
httpd = HTTPServer(server_address, HelloRequestHandler)
httpd.serve_forever()
